name: fedLabSync
channels:
  - defaults
  - conda-forge
dependencies:
  - conda==4.10.3
  - python==3.7.7
  - pip==21.2.4
  - setuptools==52.0.0
  - tk==8.6.10
  - wheel==0.37.0
  - numpy==1.21.5
  - psg_utils==0.1.6
  - typing-extensions==4.7.0rc1
  - tensorflow==2.10.0
  - pyarrow
  - tables
  - carbontracker
  - tensorflow_addons
